package menubar;
import java.awt.Color;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class JFrame_menuBar extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_menuBar
     */
    public JFrame_menuBar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelColor = new javax.swing.JLabel();
        lblGato = new javax.swing.JLabel();
        lblGatoGif = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuVentana = new javax.swing.JMenu();
        menuColores = new javax.swing.JMenu();
        itemMenuColorVentana1 = new javax.swing.JMenuItem();
        itemMenuColorVentana2 = new javax.swing.JMenuItem();
        itemMenuSalir = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuLabel = new javax.swing.JMenu();
        menuColoresLabel = new javax.swing.JMenu();
        itemMenuColorLabel1 = new javax.swing.JMenuItem();
        itemMenuColorLabel2 = new javax.swing.JMenuItem();
        menuImagen = new javax.swing.JMenu();
        itemMenuImagen1 = new javax.swing.JMenuItem();
        itemMenuImagen2 = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        itemMenuCreador = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuVentana.setText("Ventana");
        menuVentana.setToolTipText("");

        menuColores.setForeground(new java.awt.Color(0, 0, 0));
        menuColores.setText("Colores");

        itemMenuColorVentana1.setText("Color 1");
        itemMenuColorVentana1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuColorVentana1ActionPerformed(evt);
            }
        });
        menuColores.add(itemMenuColorVentana1);

        itemMenuColorVentana2.setText("Color 2");
        itemMenuColorVentana2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuColorVentana2ActionPerformed(evt);
            }
        });
        menuColores.add(itemMenuColorVentana2);

        menuVentana.add(menuColores);

        itemMenuSalir.setText("Salir");
        itemMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuSalirActionPerformed(evt);
            }
        });
        menuVentana.add(itemMenuSalir);
        menuVentana.add(jSeparator1);

        jMenuBar1.add(menuVentana);

        menuLabel.setText("Label");

        menuColoresLabel.setText("Colores");

        itemMenuColorLabel1.setText("Color 1");
        itemMenuColorLabel1.setToolTipText("");
        itemMenuColorLabel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuColorLabel1ActionPerformed(evt);
            }
        });
        menuColoresLabel.add(itemMenuColorLabel1);

        itemMenuColorLabel2.setText("Color 2");
        itemMenuColorLabel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuColorLabel2ActionPerformed(evt);
            }
        });
        menuColoresLabel.add(itemMenuColorLabel2);

        menuLabel.add(menuColoresLabel);

        menuImagen.setText("Imagenes");

        itemMenuImagen1.setText("Imagen 1");
        itemMenuImagen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuImagen1ActionPerformed(evt);
            }
        });
        menuImagen.add(itemMenuImagen1);

        itemMenuImagen2.setText("Imagen 2");
        itemMenuImagen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuImagen2ActionPerformed(evt);
            }
        });
        menuImagen.add(itemMenuImagen2);

        menuLabel.add(menuImagen);

        jMenuBar1.add(menuLabel);

        menuAbout.setText("About");

        itemMenuCreador.setText("Creador");
        itemMenuCreador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuCreadorActionPerformed(evt);
            }
        });
        menuAbout.add(itemMenuCreador);

        jMenuBar1.add(menuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelColor, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGatoGif, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGato, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGato, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGatoGif, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelColor, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuColorVentana2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuColorVentana2ActionPerformed
        this.getContentPane().setBackground(Color.decode("#f0c095"));
    }//GEN-LAST:event_itemMenuColorVentana2ActionPerformed

    private void itemMenuColorVentana1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuColorVentana1ActionPerformed
        this.getContentPane().setBackground(Color.decode("#46220f"));
    }//GEN-LAST:event_itemMenuColorVentana1ActionPerformed

    private void itemMenuColorLabel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuColorLabel1ActionPerformed
        labelColor.setOpaque(true);
        labelColor.setBackground(Color.decode("#704214"));
    }//GEN-LAST:event_itemMenuColorLabel1ActionPerformed

    private void itemMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemMenuSalirActionPerformed

    private void itemMenuCreadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuCreadorActionPerformed
        JOptionPane.showMessageDialog(null, "PlansVsAngry999");
    }//GEN-LAST:event_itemMenuCreadorActionPerformed

    private void itemMenuImagen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuImagen1ActionPerformed
            //Aqui se declara la ruta del archivo, pero no se usa en estre programa
        URL iconsUrl = getClass().getResource("src/icons/gatoCabeza.png");
            //Aqui se declara el objeto y se le asigna la ruta del archivo
        ImageIcon ni = new ImageIcon("src/icons/gatoCabeza.png");
            //Se coloca la imagen en el Label.
        lblGato.setIcon(ni);
    }//GEN-LAST:event_itemMenuImagen1ActionPerformed

    private void itemMenuImagen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuImagen2ActionPerformed
        URL iconsUrl = getClass().getResource("/src/icons/cat.gif");
        ImageIcon gif = new ImageIcon("src/icons/cat.gif");
        lblGatoGif.setIcon(gif);
    }//GEN-LAST:event_itemMenuImagen2ActionPerformed

    private void itemMenuColorLabel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuColorLabel2ActionPerformed
        labelColor.setOpaque(true);
        labelColor.setBackground(Color.decode("#804215"));
    }//GEN-LAST:event_itemMenuColorLabel2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_menuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_menuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_menuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_menuBar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_menuBar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemMenuColorLabel1;
    private javax.swing.JMenuItem itemMenuColorLabel2;
    private javax.swing.JMenuItem itemMenuColorVentana1;
    private javax.swing.JMenuItem itemMenuColorVentana2;
    private javax.swing.JMenuItem itemMenuCreador;
    private javax.swing.JMenuItem itemMenuImagen1;
    private javax.swing.JMenuItem itemMenuImagen2;
    private javax.swing.JMenuItem itemMenuSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel labelColor;
    private javax.swing.JLabel lblGato;
    private javax.swing.JLabel lblGatoGif;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenu menuColores;
    private javax.swing.JMenu menuColoresLabel;
    private javax.swing.JMenu menuImagen;
    private javax.swing.JMenu menuLabel;
    private javax.swing.JMenu menuVentana;
    // End of variables declaration//GEN-END:variables
}
